### ISSUE TITLE
support python 3.6/3.7 on travis

### ISSUE THREAD

**Issue by micahjsmith** [DAI-Lab/cookiecutter-pypackage#24]
For python 3.7, provide travis support using 
```
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
```

See https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

As we have experienced deploy errors on the xenial dist required for python 3.7, make sure to deploy on python 3.6 only, i.e.

```
deploy:
  - provider: pages
    on:
      python: 3.6
```
